package view;

public class MenuView extends javax.swing.JFrame {

    
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_menu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_cadastrarLivros = new javax.swing.JButton();
        btn_consultarLivros = new javax.swing.JButton();
        btn_cadastrarEmprestimo = new javax.swing.JButton();
        btn_consultarEmprestimos = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu2.setText("jMenu2");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(141, 124, 108));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(162, 173, 145), new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(219, 219, 219));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        lbl_menu.setBackground(new java.awt.Color(162, 173, 145));
        lbl_menu.setFont(new java.awt.Font("Perpetua", 1, 48)); // NOI18N
        lbl_menu.setForeground(new java.awt.Color(81, 71, 75));
        lbl_menu.setText("Menu Principal");

        btn_cadastrarLivros.setBackground(new java.awt.Color(204, 204, 204));
        btn_cadastrarLivros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cadastrarLivros.setForeground(new java.awt.Color(0, 0, 0));
        btn_cadastrarLivros.setText("Cadastrar Livros");
        btn_cadastrarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarLivrosActionPerformed(evt);
            }
        });

        btn_consultarLivros.setBackground(new java.awt.Color(204, 204, 204));
        btn_consultarLivros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_consultarLivros.setForeground(new java.awt.Color(0, 0, 0));
        btn_consultarLivros.setText("Consultar Livros");
        btn_consultarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarLivrosActionPerformed(evt);
            }
        });

        btn_cadastrarEmprestimo.setBackground(new java.awt.Color(204, 204, 204));
        btn_cadastrarEmprestimo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cadastrarEmprestimo.setForeground(new java.awt.Color(0, 0, 0));
        btn_cadastrarEmprestimo.setText("Cadastrar Emprestimo");
        btn_cadastrarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarEmprestimoActionPerformed(evt);
            }
        });

        btn_consultarEmprestimos.setBackground(new java.awt.Color(204, 204, 204));
        btn_consultarEmprestimos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_consultarEmprestimos.setForeground(new java.awt.Color(0, 0, 0));
        btn_consultarEmprestimos.setText("Consultar Emprestimos");
        btn_consultarEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarEmprestimosActionPerformed(evt);
            }
        });

        btn_sair.setBackground(new java.awt.Color(204, 204, 204));
        btn_sair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_sair.setForeground(new java.awt.Color(0, 0, 0));
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_menu)
                    .addComponent(btn_cadastrarLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_consultarLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cadastrarEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_consultarEmprestimos, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                        .addComponent(btn_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbl_menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cadastrarLivros)
                .addGap(31, 31, 31)
                .addComponent(btn_consultarLivros)
                .addGap(35, 35, 35)
                .addComponent(btn_cadastrarEmprestimo)
                .addGap(28, 28, 28)
                .addComponent(btn_consultarEmprestimos)
                .addGap(20, 20, 20)
                .addComponent(btn_sair)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(116, 116, 116))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(121, 121, 121))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        this.setVisible(false);
        LoginView login = new LoginView();
        login.setVisible(true);
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_consultarEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarEmprestimosActionPerformed
        this.setVisible(false);
        ConsultarEmprestimosView consultarEmprestimos = new ConsultarEmprestimosView();
        consultarEmprestimos.setVisible(true);
    }//GEN-LAST:event_btn_consultarEmprestimosActionPerformed

    private void btn_cadastrarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarEmprestimoActionPerformed
        this.setVisible(false);
        CadastrarEmprestimoView cadastrarEmprestimo = new CadastrarEmprestimoView();
        cadastrarEmprestimo.setVisible(true);
    }//GEN-LAST:event_btn_cadastrarEmprestimoActionPerformed

    private void btn_consultarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarLivrosActionPerformed
        this.setVisible(false);
        ConsultarLivrosView consultarLivros = new ConsultarLivrosView();
        consultarLivros.setVisible(true);
    }//GEN-LAST:event_btn_consultarLivrosActionPerformed

    private void btn_cadastrarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarLivrosActionPerformed
        CadastrarLivrosView cadastrarLivros = new CadastrarLivrosView();
        this.setVisible(false);    
        cadastrarLivros.setVisible(true);
    }//GEN-LAST:event_btn_cadastrarLivrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrarEmprestimo;
    private javax.swing.JButton btn_cadastrarLivros;
    private javax.swing.JButton btn_consultarEmprestimos;
    private javax.swing.JButton btn_consultarLivros;
    private javax.swing.JButton btn_sair;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JLabel lbl_usuario;
    // End of variables declaration//GEN-END:variables
}
